language: r

cache: packages

warnings_are_errors: false

before_install:
 - cd /home/travis/build/courtiol/IsoriX/IsoriX/

r:
  - oldrel
  - release
  - devel

r_packages:
  - rgl
  - covr
  - magick
  - lattice
  - maps
  - testthat

script: 
  - R CMD build .
  - travis_wait R CMD check --as-cran IsoriX*tar.gz
    
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - ghostscript
      - libnlopt-dev
      - libmagick++-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
    update: true

after_success:
  - travis_wait Rscript -e 'covr::codecov(type = "examples")'
