# Introduction

Welcome to the official documentation for the R package [__IsoriX__](https://github.com/courtiol/IsoriX_project).
This bookdown (a particular form of R documentation) explains how to use IsoriX and provide information about the underlying methods.
The content will keep evolving so to remain up to date with the current version of IsoriX, as well as to become progressively more complete and accurate.
In early versions of IsoriX, the documentation was included as vignettes attached to the package, but we have decided to move the content here.
That way, we can include more content, display better pictures and update the documentation independently from the package.

## What is IsoriX?

IsoriX is an R package that can be used for building isoscapes and inferring the geographic origin of organisms based on their isotopic signature [@IsoriX].
This package employs a new statistical framework for doing all of this which is based on mixed models (GLMM).
As most other packages dedicated to specific applications, IsoriX is essentially a simple interface to several other packages more general in scope.
Specifically, it uses the package [**spaMM**](https://kimura.univ-montp2.fr/~rousset/spaMM.htm) for fitting and predicting isoscapes, and for performing the assignment.
IsoriX also heavily relies on the package [**rasterVis**](https://oscarperpinan.github.io/rastervis/) for plotting the maps using the powerful [**lattice**](http://lattice.r-forge.r-project.org) visualization system.
Knowing these packages is not necessary to handle IsoriX but it certainly helps for advanced applications.

## Who are we?

The IsoriX core Team is so far constituted by:

  * Alexandre Courtiol
  * François Rousset
  * Marie-Sophie Rohwaeder
  * Stephanie Kramer-Schadt

Alex does the programming for IsoriX.
François does the programming for spaMM so as to make IsoriX working always better.
Alex and François are also the ones that have cooked up together the statistical framework behind IsoriX.
Marie helped with some of the programming during a short internship with Alex. 
Stephanie is the person who initiated this project and who has co-supervised many students whose project relied on IsoriX.
Alex and Stephanie are all based in the Leibniz Institute for Zoo and Wildlife Research in Berlin (Germany).
François is based at the Institut des Sciences de l'Evolution in Montpellier (France).
We are indebted to other scientists who have helped us one way or another and the extended IsoriX family consists of all the authors list in the main IsoriX publication [@IsoriX]:

```{r citation}
print(citation(package = "IsoriX")[[1]], bibtex = FALSE)
```

## Who are you?

We don't know all IsoriX users but we would love to!
For us it is important to know who uses IsoriX in order to best allocate our efforts and make IsoriX better for those who use it.
So if you are thinking of using IsoriX, please subscribe to our [Google group (a mailing list)](https://groups.google.com/g/IsoriX) and feel free to write us a little message about your project.

In this documentation, we will try to please from the very newbie to the experienced users. We will however assume that you already know R a little bit.
If it is not the case, you should read [_an Introduction to R_](https://cran.r-project.org/doc/manuals/r-release/R-intro.html) or any other introduction to R before continuing.
We will also assume that you all know a little bit about stable isotopes and isoscapes.
For the stats bits, we will also assume that you now Generalized Linear Models and hopefully a little bit about mixed models too.

## Wanna help?

If you want to help us to make IsoriX great, there are plenty things you could do irrespective of your knownledge and skills. Please check chapter \@ref(contrib) for details.


## Acknowledgements

Three wise men have been instrumental in the conception of this project: Christian Voigt, Keith Hobson and Leonar Wassenaar.
We thank them very much for their moral support and for never having given up on us.
